apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kohen.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kohen.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.operatorConfig | nindent 4 }}
