{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kohen.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kohen.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kohen.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
